# Generated by Django 5.1.4 on 2025-02-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookingroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'check_in', 'check_out')},
        ),
    ]
