# Generated by Django 5.1.4 on 2025-02-03 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_booking_room_remove_booking_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='main.booking'),
        ),
    ]
