# Generated by Django 5.1.4 on 2025-02-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bookingroom_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
